name: Build
on:
  push:
    branches: [ "**", "!main" ]
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:

jobs:
  publish_packages:
    name: Build
    uses: yaml-js/.github/.github/workflows/jobs.build.yml@main
    permissions:
      contents: write
      pull-requests: write
    with:
      KEY: ${{ github.sha }}
      EVENT: ${{ github.event_name }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
